table UpdateMsIntermediate {
    update_type: string;
    ms: float32;
}

table UpdateMsIntermediateDiff {
    key: [ubyte];
    old_update_type: string;
    new_update_type: string;
    old_ms: float32;
    new_ms: float32;
}

table UpdateMsAccumulator {
    by_type: [UpdateMsAggregateByType];
    percentiles: [UpdateMsPercAcc];
}

table UpdateMsPercAcc {
    percentile: UpdateMsPerc;
    key_pos: uint32;
    keys_around: [ubyte];
    next_request_id: uint32;
    next_request_is_forward: bool;
}

table UpdateMsAggregateByType {
    key: string;
    sum_ms: float64;
    count: ulong;
}

table UpdateMsPerc {
    percentile: float32;
    /// optional, if collection is empty
    intermediate_key: [ubyte];
}

table UpdateMsPercentiles {
    sum_ms: float64;
    by_type: [UpdateMsAggregateByType];
    percentiles: [UpdateMsPerc];
}
