[package]
name = "diffbelt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
warp = "0.3.3"
futures = "0.3.25"
rocksdb = { version = "0.19.0", features = ["multi-threaded-cf"] }
protobuf = "3.2.0"
rand = "0.8.5"

[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-rust = "2.28.0"
