make:
	cargo build --release --target wasm32-unknown-unknown

debug:
	cargo build --target wasm32-unknown-unknown
	cp target/wasm32-unknown-unknown/debug/diffbelt_example_wasm.wasm target/wasm32-unknown-unknown/release/diffbelt_example_wasm.wasm

