[package]
name = "diffbelt_cli_config"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.diffbelt_util]
path = "../diffbelt_util"

[dependencies.yaml-peg]
git = "https://github.com/Rulexec/yaml-peg-rs.git"
rev = "962db9aae5c0dfab560b3ab1647b955178a16f31"
