table StartGenerationRequest {
  collection_name: string;
  generation_id: [ubyte];
  abort_outdated: bool = false;
}

table StartGenerationResponse {}

table ReaderUpdate {
    reader_name: string;
    generation_id: [ubyte];
}

table CommitGenerationRequest {
  generation_id: [ubyte];
  /// optional
  update_readers: [ReaderUpdate];
}

table CommitGenerationResponse {}

table GenerationIdStreamRequest {
  collection_name: string;
  /// optional
  generation_id: [ubyte];
  /// optional
  to_generation_id: [ubyte];
}

table GenerationIdStreamResponse {
  generation_id: [ubyte];
}
