[package]
name = "diffbelt-percentiles-calculator-test"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version ="0.8.5", default-features = false }
enum-as-inner = "0.6.0"

[dependencies.diffbelt_percentiles_calculator]
path = "../diffbelt_percentiles_calculator"

[dependencies.diffbelt_util_no_std]
path = "../diffbelt_util_no_std"
