[package]
name = "diffbelt_util_no_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror-no-std = { version = "2.0.2", default-features = false }
either = "1.9.0"

